# Generated by Django 3.2.3 on 2021-06-02 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today, null=True, verbose_name='дата заявки'),
        ),
    ]
