# Generated by Django 3.2.3 on 2021-06-02 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0002_alter_application_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='дата заявки'),
        ),
    ]
